apiVersion: v1
kind: Service
metadata:
  name: sentiment-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: sentiment
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: sentiment
    tier: frontend
  ports:
  - port: {{ .Values.frontendPort }}
    targetPort: http-server
