apiVersion: v1
kind: Service
metadata:
  name: sentiment-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: sentiment
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: sentiment
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
