- hosts: localhost
  vars:
     http_port: 80
  tasks:
  - name: update apk
    command: apk update
  - name: install nginx
    command: apk add nginx
  - name: add nginx service
    command: rc-update add nginx default